### ISSUE TITLE
Sistema de Autenticação e Autorização

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Requirewoments/2020.1-WeServe-Backend#16]
Deve ser implementado um sistema de autenticação e autorização, para que seja possível o usuário realizar login, bem como acessar determinadas partes do app somente se estiver logado.

**Comment by VictorAmaralC** [comment]
**Descrição**

Foi implementado nesta issue o sistema de autentificacao e verificacao de usuarios no login do sistema

## Objetivo
Registrar servico de verificacao/autenticacao de usuario

## Padrões de aceitação:

- [x] Sem conflitos com o ramo principal do projeto.
- [x] Pull request vinculado a uma issue.
